### ISSUE TITLE
Feature Request. Css from another file (.css file)

### ISSUE THREAD

**Issue by TheMcMurder** [CanopyTax/kremling#4]
I'm pretty sold on the ideas behind Kremling, the one thing I don't like is using a template string to define CSS

It would be really nice to have a css file that I could import and use.

**Comment by joeldenning** [comment]
You can do this with webpack loaders! I need to add some documentation for it, but you basically want the css-loader without the style-loader, so that you can get the css file as a string. Or another option is to use the file-loader or the html-loader.

I'll play around with this in a few hours and put together some documentation.

```
import css from './file.css'

<Scoped css={css}>
</Scoped>
```

**Comment by geoctrl** [comment]
@TheMcMurder - this is doable with the `postcss-prepend-selector` plugin - you pipe it through post-css, then the raw-loader.

```js
{
  test: /\.css$/,
  use: [
    'raw-loader',
    {
      loader: 'postcss-loader',
      options: {
        plugins() {
          return [
            require('autoprefixer'),
            require('postcss-prepend-selector')({ selector: '& '}),
          ];
        },
      },
    },
  ],
},
```

styles.css:
```css
.main {
  background-color: red;
}
```

import it:
```js
import { Scoped } from 'kremling';
import css from './styles.css';

() => (
  <Scoped css={css}>
    <div className="main">heyo</div>
  </Scoped>
);
```

**Comment by geoctrl** [comment]
@TheMcMurder https://github.com/CanopyTax/kremling-loader

**Comment by joeldenning** [comment]
Closing this since we now have a full solution for it
